# hosts/pi/default.nix
#
# Raspberry Pi 5 NixOS configuration.
#
# Roles:
#   1. Encrypted storage appliance — two LUKS-encrypted 4 TB drives
#      automatically unlocked via Clevis/Tang on the main server.
#   2. NFS export of both drives to the server.
#   3. TV/sofa frontend — Kodi and RetroArch via a simple launcher.
#
# This config is intentionally minimal.  Heavy compute, databases,
# indexing, and container orchestration all live on the server.
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware — generated by nixos-generate-config on the Pi.
    # The nixos-hardware raspberry-pi-5 module (from flake input) is
    # applied in flake.nix.
    ./hardware-configuration.nix

    # Shared modules
    ../../modules/common/settings.nix
    ../../modules/common/base.nix
    ../../modules/common/users.nix
    ../../modules/common/ssh.nix
    ../../modules/common/auto-upgrade.nix

    # Pi-specific modules
    ../../modules/pi/clevis-unlock.nix
    ../../modules/pi/launcher.nix

    # Pi service modules
    ./services/storage.nix
    ./services/nfs-exports.nix
    ./services/frontend.nix
    ./services/snapclient.nix
    ./services/wyoming-satellite.nix
    ./services/telegraf.nix
  ];

  # ---------------------------------------------------------------------------
  # Unattended upgrades
  # ---------------------------------------------------------------------------
  # The git pull pre-service is in modules/common/auto-upgrade.nix.
  # allowReboot is true — the Pi unlocks its drives via Clevis/Tang
  # automatically on reboot, so unattended reboots are safe as long as the
  # server (and Tang) are running.  The reboot window keeps reboots in the
  # early hours so they don't interrupt evening use.
  system.autoUpgrade = {
    enable      = true;
    flake       = "/etc/nixos#pi";
    flags       = [ "--impure" ];
    allowReboot = true;
    rebootWindow = {
      lower = "04:00";
      upper = "06:00";
    };
    dates       = "04:30";
    randomizedDelaySec = "30min";
  };

  # ---------------------------------------------------------------------------
  # Identity
  # ---------------------------------------------------------------------------
  networking.hostName = config.lanbat.piHostname;

  # ---------------------------------------------------------------------------
  # Networking
  # ---------------------------------------------------------------------------
  networking = {
    useNetworkd = true;
    # Static IP recommended — server Tang client needs a stable target.
    interfaces.eth0 = {
      useDHCP = false;
      ipv4.addresses = [{
        address      = config.lanbat.piIp;
        prefixLength = 24;
      }];
    };
    defaultGateway = config.lanbat.gatewayIp;
    nameservers    = [ config.lanbat.gatewayIp ];
  };

  # Firewall — Pi only needs SSH + NFS from server + Wyoming satellite from server.
  networking.firewall = {
    enable          = true;
    allowedTCPPorts = [ 22 2049 111 10700 ];
    allowedUDPPorts = [ 5353 ];  # mDNS — Wyoming satellite auto-discovery by HA
    # Restrict NFS to the server's IP.
    # Wyoming satellite (10700) is also restricted to the server.
    extraCommands = ''
      iptables -I INPUT -p tcp --dport 2049  ! -s ${config.lanbat.serverIp} -j DROP
      iptables -I INPUT -p udp --dport 2049  ! -s ${config.lanbat.serverIp} -j DROP
      iptables -I INPUT -p tcp --dport 10700 ! -s ${config.lanbat.serverIp} -j DROP
    '';
  };

  # ---------------------------------------------------------------------------
  # NTP — sync time from server (optional) or pool.
  # ---------------------------------------------------------------------------
  services.timesyncd.enable = true;

  # ---------------------------------------------------------------------------
  # Secrets (agenix)
  # ---------------------------------------------------------------------------
  # Pi currently has no secrets managed by agenix.
  # Add here if needed (e.g., MQTT credentials, VPN keys).

  # ---------------------------------------------------------------------------
  # Admin user
  # ---------------------------------------------------------------------------
  users.users.admin = {
    isNormalUser = true;
    uid          = 1001;
    extraGroups  = [ "wheel" ];
    openssh.authorizedKeys.keys = [ config.lanbat.adminSshKey ];
  };

  # ---------------------------------------------------------------------------
  # Minimal package set — Pi should stay lean.
  # ---------------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    clevis
    tang
    nfs-utils
    xfsprogs
    cryptsetup
    smartmontools
  ];

  system.stateVersion = "24.11";
}
