# hosts/server/default.nix
#
# Main server NixOS configuration.
# Imports all shared modules and service sub-modules.
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware — generated by nixos-generate-config, must be provided manually.
    ./hardware-configuration.nix

    # Shared modules
    ../../modules/common/settings.nix
    ../../modules/common/base.nix
    ../../modules/common/users.nix
    ../../modules/common/ssh.nix
    ../../modules/common/auto-upgrade.nix

    # Server-specific modules
    ../../modules/server/secure-layers.nix        # three-layer LUKS design
    ../../modules/server/workload-gate.nix         # service gating on workload
    ../../modules/server/backups.nix               # restic backup framework
    ../../modules/server/nfs-mounts.nix
    ../../modules/server/nfs-dependent-service.nix
    ../../modules/server/on-demand.nix

    # Service modules
    ./services/tang.nix
    ./services/caddy.nix
    ./services/authentik.nix
    ./services/authentik-blueprints.nix
    ./services/home-assistant.nix
    ./services/nextcloud.nix
    ./services/immich.nix
    ./services/jellyfin.nix
    ./services/qbittorrent.nix
    ./services/frigate.nix
    ./services/bitmagnet.nix
    ./services/searxng.nix
    ./services/homepage.nix
    ./services/samba.nix
    ./services/mosquitto.nix
    ./services/zigbee2mqtt.nix
    ./services/vaultwarden.nix
    ./services/influxdb.nix
    ./services/grafana.nix
    ./services/syncthing.nix
    ./services/snapcast.nix
    ./services/wyoming.nix
    ./services/telegraf.nix
  ];

  # ---------------------------------------------------------------------------
  # Identity
  # ---------------------------------------------------------------------------
  networking.hostName = config.lanbat.serverHostname;

  # ---------------------------------------------------------------------------
  # Unattended upgrades
  # ---------------------------------------------------------------------------
  # The git pull pre-service is in modules/common/auto-upgrade.nix.
  # allowReboot is false — after a reboot, both LUKS layers stay locked until
  # an admin manually runs unlock-control and unlock-workload.  An unattended
  # reboot would leave the server in host-only mode with no services running.
  system.autoUpgrade = {
    enable      = true;
    flake       = "/etc/nixos#server";
    flags       = [ "--impure" ];
    allowReboot = false;
    dates       = "04:00";
    randomizedDelaySec = "30min";
  };

  # ---------------------------------------------------------------------------
  # Boot
  # ---------------------------------------------------------------------------
  # The server uses a three-layer design.  Host root (sda2) is plain ext4 —
  # no passphrase is required at boot.  The control (sda3) and workload (sda4)
  # LUKS volumes are opened manually after boot by an admin.
  # See modules/server/secure-layers.nix for the full design.
  # See docs/runbook.md for the unlock procedure.
  boot.loader = {
    systemd-boot.enable      = true;
    efi.canTouchEfiVariables = true;
  };
  # No boot.initrd.luks entries — neither LUKS volume opens at boot.
  # The host root (sda2) is unencrypted ext4 (declared in hardware-configuration.nix).

  # ---------------------------------------------------------------------------
  # Networking
  # ---------------------------------------------------------------------------
  networking = {
    useNetworkd = true;
    # Static address recommended for a server.
    interfaces.eno1 = {
      useDHCP = false;
      ipv4.addresses = [{
        address      = config.lanbat.serverIp;
        prefixLength = 24;
      }];
    };
    defaultGateway = { address = config.lanbat.gatewayIp; interface = "eno1"; };
    nameservers    = [ config.lanbat.gatewayIp "1.1.1.1" ];

    # IPv6 — accept RA from router; do not expose services by default.
    # Caddy will also bind on IPv6 for frontend access; everything else stays v4.
    interfaces.eno1.ipv6.addresses = [
      # Uncomment and set a ULA or GUA once ready.
      # { address = "EXAMPLE_IPV6"; prefixLength = 64; }
    ];
  };

  # Firewall — allow only what is needed.
  networking.firewall = {
    enable = true;
    # TCP ports open to the LAN.
    allowedTCPPorts = [
      22    # SSH
      80    # Caddy HTTP (redirects to HTTPS)
      443   # Caddy HTTPS
      7500  # Tang key server (Pi Clevis unlock)
      2049  # NFS (restricted to Pi via extraCommands below)
      111   # NFSv4 — optional, may remove
      8086  # InfluxDB (restricted to Pi via extraCommands below)
    ];
    # Restrict NFS and InfluxDB to the Pi's IP only.
    extraCommands = ''
      iptables -I INPUT -p tcp --dport 2049 ! -s ${config.lanbat.piIp} -j DROP
      iptables -I INPUT -p udp --dport 2049 ! -s ${config.lanbat.piIp} -j DROP
      iptables -I INPUT -p tcp --dport 8086 ! -s ${config.lanbat.piIp} -j DROP
    '';
    allowedUDPPorts = [
      5353  # mDNS (Home Assistant discovery)
    ];
  };

  # ---------------------------------------------------------------------------
  # Container runtime (Podman)
  # ---------------------------------------------------------------------------
  virtualisation.podman = {
    enable             = true;
    dockerCompat       = true;    # provide a "docker" shim
    defaultNetwork.settings.dns_enabled = true;
    autoPrune.enable   = true;
    autoPrune.dates    = "weekly";
  };

  virtualisation.oci-containers.backend = "podman";

  # ---------------------------------------------------------------------------
  # Shared databases (PostgreSQL + Redis)
  # ---------------------------------------------------------------------------
  # Authentik, Nextcloud, and Bitmagnet share a single PostgreSQL instance.
  # Each service gets its own database and user.
  # Shared PostgreSQL instance for Authentik, Nextcloud, Bitmagnet, and Immich.
  # Immich previously used its own containerized PostgreSQL (pgvecto.rs), but
  # vectorchord (pgvecto.rs successor) is now available in nixpkgs for pg16.
  services.postgresql = {
    enable  = true;
    # Use unstable postgresql_16 — 24.11 stable doesn't include vectorchord
    # (required by Immich for vector/ML search). Minor version upgrades are
    # backward-compatible so no data migration is needed.
    package     = pkgs.unstable.postgresql_16;
    extensions  = _: with pkgs.unstable.postgresql16Packages; [ pgvector vectorchord ];

    # Listen on localhost only; containers access via --network host.
    settings = {
      listen_addresses = lib.mkForce "127.0.0.1";
      # vectorchord requires preloading its shared library.
      shared_preload_libraries = "vchord.so";
      # Authentik (Django + Celery) + Nextcloud + Immich + Bitmagnet exhaust
      # the default of 100.  200 leaves headroom without excessive memory cost.
      max_connections = 200;
    };

    authentication = lib.mkForce ''
      # TYPE  DATABASE        USER            ADDRESS           METHOD
      local   all             all                               peer
      host    all             all             127.0.0.1/32      scram-sha-256
    '';

    ensureDatabases = [
      "authentik"
      "nextcloud"
      "bitmagnet"
      "immich"
    ];

    ensureUsers = [
      { name = "authentik";  ensureDBOwnership = true; }
      { name = "nextcloud";  ensureDBOwnership = true; }
      { name = "bitmagnet";  ensureDBOwnership = true; }
      { name = "immich";     ensureDBOwnership = true; }
    ];
  };

  # Set the authentik PostgreSQL password (needed for TCP auth from the container).
  # Runs after postgresql.service each boot; idempotent.
  systemd.services."postgresql-authentik-init" = {
    description = "Initialize Authentik PostgreSQL user password";
    after    = [ "postgresql.service" ];
    wantedBy = [ "postgresql.service" ];
    unitConfig.ConditionPathExists = config.age.secrets.authentik-env.path;
    serviceConfig = {
      Type            = "oneshot";
      RemainAfterExit = true;
      User            = "postgres";
      ExecStart = pkgs.writeShellScript "postgresql-authentik-init" ''
        set -euo pipefail
        AUTHENTIK_POSTGRESQL__PASSWORD=""
        source ${config.age.secrets.authentik-env.path}
        ${config.services.postgresql.package}/bin/psql -c "ALTER USER authentik WITH ENCRYPTED PASSWORD '$AUTHENTIK_POSTGRESQL__PASSWORD';"
      '';
    };
  };

  # Set the immich PostgreSQL password (needed for TCP auth from the container).
  # Runs after postgresql.service each boot; idempotent.
  systemd.services."postgresql-immich-init" = {
    description = "Initialize Immich PostgreSQL user password and extension";
    after    = [ "postgresql.service" ];
    wantedBy = [ "postgresql.service" ];
    unitConfig.ConditionPathExists = config.age.secrets.immich-db-password.path;
    serviceConfig = {
      Type            = "oneshot";
      RemainAfterExit = true;
      User            = "postgres";
      ExecStart = pkgs.writeShellScript "postgresql-immich-init" ''
        set -euo pipefail
        POSTGRES_PASSWORD=""
        source ${config.age.secrets.immich-db-password.path}
        ${config.services.postgresql.package}/bin/psql -c "ALTER USER immich WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';"
        ${config.services.postgresql.package}/bin/psql -d immich -c "CREATE EXTENSION IF NOT EXISTS vchord CASCADE;"
      '';
    };
  };

  # Set the bitmagnet PostgreSQL password (needed for TCP auth from the container).
  systemd.services."postgresql-bitmagnet-init" = {
    description = "Initialize Bitmagnet PostgreSQL user password";
    after    = [ "postgresql.service" ];
    wantedBy = [ "postgresql.service" ];
    unitConfig.ConditionPathExists = config.age.secrets.bitmagnet-db-pass.path;
    serviceConfig = {
      Type            = "oneshot";
      RemainAfterExit = true;
      User            = "postgres";
      ExecStart = pkgs.writeShellScript "postgresql-bitmagnet-init" ''
        set -euo pipefail
        POSTGRES_PASSWORD=""
        source ${config.age.secrets.bitmagnet-db-pass.path}
        ${config.services.postgresql.package}/bin/psql -c "ALTER USER bitmagnet WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';"
      '';
    };
  };

  # linger-users.service is generated by NixOS and fires once per container user
  # during switch-to-configuration.  With many container users it hits the
  # default start-rate-limit and appears failed even though each run succeeds.
  # Removing the rate limit suppresses the false alarm.
  systemd.services.linger-users.unitConfig.StartLimitIntervalSec = lib.mkForce 0;

  # Redis — single shared instance; services use separate DB numbers.
  #   DB 0 — Authentik  (sessions, cache)
  #   DB 1 — Immich     (job queues, cache)
  # Both consumers set save=[] (ephemeral), so data is safe to lose on restart.
  services.redis.servers.shared = {
    enable = true;
    port   = 6379;
    bind   = "127.0.0.1";
    save   = [];
  };

  # ---------------------------------------------------------------------------
  # Server-local state directories
  # ---------------------------------------------------------------------------
  # NOTE: /var/lib/* service data directories are created as mode-0000 stubs
  # by modules/server/secure-layers.nix.  They are bind-mounted from the
  # workload LUKS layer by modules/server/workload-gate.nix when that layer
  # is unlocked.  Do NOT add /var/lib/authentik, /var/lib/immich, etc. here.
  systemd.tmpfiles.rules = [
    # Non-sensitive host-root directories (not service data, no workload bind mount needed).
    "d /var/lib/homelab    0755 root root -"
    "d /var/lib/ca-landing 0755 root root -"

    # Transient caches — these can live on host root (derived, re-generatable).
    # On a busy server, move these to a separate tmpfs or workload subdir.
    "d /var/cache/jellyfin 0750 jellyfin jellyfin -"
    "d /var/cache/frigate  0750 frigate  frigate  -"
  ];

  # ---------------------------------------------------------------------------
  # Secrets (agenix)
  # ---------------------------------------------------------------------------
  # Secret files are encrypted .age files in secrets/.
  # See secrets/README.md for how to create them.
  age.secrets = {
    # ---- Authentik ----
    # File format (two KEY=value lines):
    #   AUTHENTIK_POSTGRESQL__PASSWORD=<value>
    #   AUTHENTIK_SECRET_KEY=<50+ random chars>
    # group = "postgres" + mode 0440: both authentik (owner) and postgres (group)
    # can read — needed for postgresql-authentik-init which runs as postgres.
    authentik-env = { file = ../../secrets/authentik-env.age; owner = "authentik"; group = "postgres"; mode = "0440"; };

    # ---- Nextcloud ----
    # nextcloud-db-pass removed — using createLocally = true (Unix socket, no password)
    nextcloud-admin-pass = { file = ../../secrets/nextcloud-admin-pass.age; owner = "nextcloud"; };
    # File format:
    #   NEXTCLOUD_OIDC_CLIENT_ID=<value>
    #   NEXTCLOUD_OIDC_CLIENT_SECRET=<value>
    nextcloud-oidc-env   = { file = ../../secrets/nextcloud-oidc-env.age;   owner = "nextcloud"; };

    # ---- Immich ----
    # File format:
    #   POSTGRES_PASSWORD=<value>
    # group = "postgres" + mode 0440: both immich (owner) and postgres (group)
    # can read — needed for postgresql-immich-init which runs as postgres.
    immich-db-password   = { file = ../../secrets/immich-db-password.age;   owner = "immich"; group = "postgres"; mode = "0440"; };
    # File format:
    #   IMMICH_OAUTH_CLIENT_ID=<value>
    #   IMMICH_OAUTH_CLIENT_SECRET=<value>
    immich-oidc-env      = { file = ../../secrets/immich-oidc-env.age;      owner = "immich"; };

    # ---- Bitmagnet ----
    # File format: POSTGRES_PASSWORD=<value>
    bitmagnet-db-pass = { file = ../../secrets/bitmagnet-db-pass.age; owner = "bitmagnet"; group = "postgres"; mode = "0440"; };

    # ---- Frigate ----
    rclone-frigate-config = { file = ../../secrets/rclone-frigate-config.age; owner = "frigate"; };

    # ---- MQTT / Mosquitto ----
    # Each file contains a single-line plaintext password.
    mosquitto-ha-pass      = { file = ../../secrets/mosquitto-ha-pass.age;     owner = "mosquitto"; };
    mosquitto-frigate-pass = { file = ../../secrets/mosquitto-frigate-pass.age; owner = "mosquitto"; };
    mosquitto-z2m-pass     = { file = ../../secrets/mosquitto-z2m-pass.age;    owner = "mosquitto"; };

  };

  # ---------------------------------------------------------------------------
  # Human admin user
  # ---------------------------------------------------------------------------
  users.users.admin = {
    isNormalUser = true;
    uid          = 1001;
    extraGroups  = [ "wheel" "media" "private" ];
    # Set your SSH public key here.
    openssh.authorizedKeys.keys = [ config.lanbat.adminSshKey ];
  };

  # Helper scripts (domain is substituted at build time from lanbat.domain).
  environment.systemPackages = [
    (pkgs.callPackage ../../pkgs/scripts { inherit (config.lanbat) domain; })
  ];

  system.stateVersion = "24.11";
}
