# hosts/server/default.nix
#
# Main server NixOS configuration.
# Imports all shared modules and service sub-modules.
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware — generated by nixos-generate-config, must be provided manually.
    ./hardware-configuration.nix

    # Shared modules
    ../../modules/common/settings.nix
    ../../modules/common/base.nix
    ../../modules/common/users.nix
    ../../modules/common/ssh.nix
    ../../modules/common/auto-upgrade.nix

    # Server-specific modules
    ../../modules/server/nfs-mounts.nix
    ../../modules/server/nfs-dependent-service.nix
    ../../modules/server/on-demand.nix

    # Service modules
    ./services/tang.nix
    ./services/caddy.nix
    ./services/authentik.nix
    ./services/home-assistant.nix
    ./services/nextcloud.nix
    ./services/immich.nix
    ./services/jellyfin.nix
    ./services/qbittorrent.nix
    ./services/frigate.nix
    ./services/bitmagnet.nix
    ./services/searxng.nix
    ./services/homepage.nix
    ./services/samba.nix
    ./services/mosquitto.nix
    ./services/vaultwarden.nix
    ./services/influxdb.nix
    ./services/grafana.nix
    ./services/syncthing.nix
    ./services/snapcast.nix
    ./services/wyoming.nix
    ./services/telegraf.nix
  ];

  # ---------------------------------------------------------------------------
  # Identity
  # ---------------------------------------------------------------------------
  networking.hostName = config.lanbat.serverHostname;

  # ---------------------------------------------------------------------------
  # Unattended upgrades
  # ---------------------------------------------------------------------------
  # The git pull pre-service is in modules/common/auto-upgrade.nix.
  # allowReboot is false — the server requires a manual LUKS passphrase at
  # boot, so it cannot reboot unattended.  Upgrades take effect at the next
  # manual reboot or when `systemctl restart <service>` is run.
  system.autoUpgrade = {
    enable      = true;
    flake       = "/etc/nixos#server";
    flags       = [ "--impure" ];
    allowReboot = false;
    dates       = "04:00";
    randomizedDelaySec = "30min";
  };

  # ---------------------------------------------------------------------------
  # Boot / disk encryption
  # ---------------------------------------------------------------------------
  # The server uses LUKS-encrypted root.
  # During installation, partition the server disk (e.g. /dev/sda) with:
  #   p1: EFI system partition (~512 MiB, vfat)
  #   p2: LUKS container (rest of disk)
  # Then inside LUKS: LVM or a single ext4/btrfs partition.
  # See docs/deployment-checklist.md for the full partitioning guide.
  boot.loader = {
    systemd-boot.enable      = true;
    efi.canTouchEfiVariables = true;
  };

  # LUKS device — update the UUID to match your actual partition.
  boot.initrd.luks.devices."cryptroot" = {
    device     = "/dev/disk/by-uuid/CHANGE_ME_SERVER_LUKS_UUID";
    preLVM     = true;
    # Interactive passphrase prompt at boot.  No network needed.
    allowDiscards = true; # enable only on SSDs you trust
  };

  # ---------------------------------------------------------------------------
  # Networking
  # ---------------------------------------------------------------------------
  networking = {
    useNetworkd = true;
    # Static address recommended for a server.
    interfaces.eno1 = {
      useDHCP = false;
      ipv4.addresses = [{
        address      = config.lanbat.serverIp;
        prefixLength = 24;
      }];
    };
    defaultGateway = config.lanbat.gatewayIp;
    nameservers    = [ config.lanbat.gatewayIp "1.1.1.1" ];

    # IPv6 — accept RA from router; do not expose services by default.
    # Caddy will also bind on IPv6 for frontend access; everything else stays v4.
    interfaces.eno1.ipv6.addresses = [
      # Uncomment and set a ULA or GUA once ready.
      # { address = "EXAMPLE_IPV6"; prefixLength = 64; }
    ];
  };

  # Firewall — allow only what is needed.
  networking.firewall = {
    enable = true;
    # TCP ports open to the LAN.
    allowedTCPPorts = [
      22    # SSH
      80    # Caddy HTTP (redirects to HTTPS)
      443   # Caddy HTTPS
      7500  # Tang key server (Pi Clevis unlock)
      2049  # NFS (restricted to Pi via extraCommands below)
      111   # NFSv4 — optional, may remove
      8086  # InfluxDB (restricted to Pi via extraCommands below)
    ];
    # Restrict NFS and InfluxDB to the Pi's IP only.
    extraCommands = ''
      iptables -I INPUT -p tcp --dport 2049 ! -s ${config.lanbat.piIp} -j DROP
      iptables -I INPUT -p udp --dport 2049 ! -s ${config.lanbat.piIp} -j DROP
      iptables -I INPUT -p tcp --dport 8086 ! -s ${config.lanbat.piIp} -j DROP
    '';
    allowedUDPPorts = [
      5353  # mDNS (Home Assistant discovery)
    ];
  };

  # ---------------------------------------------------------------------------
  # Container runtime (Podman)
  # ---------------------------------------------------------------------------
  virtualisation.podman = {
    enable             = true;
    dockerCompat       = true;    # provide a "docker" shim
    defaultNetwork.settings.dns_enabled = true;
    autoPrune.enable   = true;
    autoPrune.dates    = "weekly";
  };

  virtualisation.oci-containers.backend = "podman";

  # ---------------------------------------------------------------------------
  # Shared databases (PostgreSQL + Redis)
  # ---------------------------------------------------------------------------
  # Authentik, Nextcloud, and Bitmagnet share a single PostgreSQL instance.
  # Each service gets its own database and user.
  # Immich uses its own containerized PostgreSQL (requires pgvecto.rs).
  services.postgresql = {
    enable  = true;
    package = pkgs.postgresql_16;

    # Listen on localhost only; containers access via --network host.
    settings.listen_addresses = "127.0.0.1";

    authentication = lib.mkForce ''
      # TYPE  DATABASE        USER            ADDRESS           METHOD
      local   all             all                               peer
      host    all             all             127.0.0.1/32      scram-sha-256
    '';

    ensureDatabases = [
      "authentik"
      "nextcloud"
      "bitmagnet"
    ];

    ensureUsers = [
      { name = "authentik";  ensureDBOwnership = true; }
      { name = "nextcloud";  ensureDBOwnership = true; }
      { name = "bitmagnet";  ensureDBOwnership = true; }
    ];
  };

  # Redis — named instances per service.
  services.redis.servers = {
    authentik = {
      enable  = true;
      port    = 6379;
      bind    = "127.0.0.1";
      save    = [];  # Authentik Redis is ephemeral; disable persistence.
    };
    immich = {
      enable  = true;
      port    = 6380;
      bind    = "127.0.0.1";
      save    = [];
    };
  };

  # ---------------------------------------------------------------------------
  # Server-local state directories
  # ---------------------------------------------------------------------------
  systemd.tmpfiles.rules = [
    # Config / state (survive reboots, should be backed up)
    "d /var/lib/homelab                0755 root     root    -"
    "d /var/lib/authentik              0750 root     root    -"
    "d /var/lib/immich                 0750 immich   immich  -"
    "d /var/lib/immich/db              0750 immich   immich  -"
    "d /var/lib/immich/upload          0750 immich   immich  -"
    "d /var/lib/immich/thumbs          0750 immich   immich  -"
    "d /var/lib/immich/encoded-video   0750 immich   immich  -"
    "d /var/lib/immich/profile         0750 immich   immich  -"
    "d /var/lib/immich/model-cache     0750 immich   immich  -"
    "d /var/lib/frigate                0750 frigate  frigate -"
    "d /var/lib/frigate/db             0750 frigate  frigate -"
    "d /var/lib/frigate/config         0750 frigate  frigate -"
    "d /var/lib/qbittorrent            0750 qbt      qbt     -"
    "d /var/lib/bitmagnet              0750 root     root    -"
    "d /var/lib/homepage               0750 root     root    -"
    "d /var/lib/ca-landing             0755 root     root    -"

    # Transcode / cache (okay to lose on reboot — put on tmpfs if desired)
    "d /var/cache/jellyfin             0750 jellyfin jellyfin -"
    "d /var/cache/frigate              0750 frigate  frigate  -"
  ];

  # ---------------------------------------------------------------------------
  # Secrets (agenix)
  # ---------------------------------------------------------------------------
  # Secret files are encrypted .age files in secrets/.
  # See secrets/README.md for how to create them.
  age.secrets = {
    # ---- Authentik ----
    # File format (two KEY=value lines):
    #   AUTHENTIK_POSTGRESQL__PASSWORD=<value>
    #   AUTHENTIK_SECRET_KEY=<50+ random chars>
    authentik-env = { file = ../../secrets/authentik-env.age; owner = "root"; };

    # ---- Nextcloud ----
    nextcloud-db-pass    = { file = ../../secrets/nextcloud-db-pass.age;    owner = "nextcloud"; };
    nextcloud-admin-pass = { file = ../../secrets/nextcloud-admin-pass.age; owner = "nextcloud"; };
    # File format:
    #   NEXTCLOUD_OIDC_CLIENT_ID=<value>
    #   NEXTCLOUD_OIDC_CLIENT_SECRET=<value>
    nextcloud-oidc-env   = { file = ../../secrets/nextcloud-oidc-env.age;   owner = "nextcloud"; };

    # ---- Immich ----
    # File format:
    #   POSTGRES_PASSWORD=<value>
    immich-db-password   = { file = ../../secrets/immich-db-password.age;   owner = "immich"; };
    # File format:
    #   IMMICH_OAUTH_CLIENT_ID=<value>
    #   IMMICH_OAUTH_CLIENT_SECRET=<value>
    immich-oidc-env      = { file = ../../secrets/immich-oidc-env.age;      owner = "immich"; };

    # ---- Frigate ----
    rclone-frigate-config = { file = ../../secrets/rclone-frigate-config.age; owner = "frigate"; };

    # ---- MQTT / Mosquitto ----
    # Each file contains a single-line plaintext password.
    mosquitto-ha-pass     = { file = ../../secrets/mosquitto-ha-pass.age;    owner = "mosquitto"; };
    mosquitto-frigate-pass = { file = ../../secrets/mosquitto-frigate-pass.age; owner = "mosquitto"; };

  };

  # ---------------------------------------------------------------------------
  # Human admin user
  # ---------------------------------------------------------------------------
  users.users.admin = {
    isNormalUser = true;
    uid          = 1001;
    extraGroups  = [ "wheel" "media" "private" ];
    # Set your SSH public key here.
    openssh.authorizedKeys.keys = [ config.lanbat.adminSshKey ];
  };

  # Helper scripts (domain is substituted at build time from lanbat.domain).
  environment.systemPackages = [
    (pkgs.callPackage ../../pkgs/scripts { inherit (config.lanbat) domain; })
  ];

  system.stateVersion = "24.11";
}
