[General]
version=2

[settings]
window_type=Fullscreen
hw_decoder=auto
resolution_local_ps5=1080p
fps_local_ps5=60
bitrate_local_ps5=30000
codec_local_ps5=h265
resolution_remote_ps5=1080p
fps_remote_ps5=60
bitrate_remote_ps5=15000
codec_remote_ps5=h265
resolution_local_ps4=720p
fps_local_ps4=60
bitrate_local_ps4=15000
codec_local_ps4=h264
