# hosts/server/services/homepage.nix
#
# Homepage — dynamic service dashboard.
#
# Serves as the main LAN landing page at home.<domain>.
# Shows all services with health widgets where supported.
# No authentication — it's the entry point.
#
# Config files are generated via pkgs.writeText and mounted read-only, so
# they update on every rebuild without any init service or "if not exists" guards.
#
# Networking
# ----------
# Homepage runs with host networking so widget requests can reach Caddy
# on 127.0.0.1:443.  Pasta networking blocks connections to the host.
#
# Caddy uses an internal CA. Its root cert is mounted into the container and
# trusted via NODE_EXTRA_CA_CERTS so widget TLS verification succeeds.
# The cert is generated by Caddy on first TLS request — if Homepage starts
# before the cert exists, widgets will error until Homepage restarts.
#
# Widget coverage
# ---------------
# Services without Authentik forward auth in Caddy have API widgets.
# Services protected by Authentik forward auth (Frigate, qBittorrent,
# Bitmagnet, Syncthing, Snapcast, Zigbee2MQTT) are shown as links only —
# their APIs are not reachable without a valid session cookie.
{ config, pkgs, lib, ... }:

let
  domain = config.lanbat.domain;

  servicesYaml = pkgs.writeText "homepage-services.yaml" ''
    - Identity & Auth:
        - Authentik:
            href: https://auth.${domain}
            description: Identity & SSO
            icon: authentik
            widget:
              type: authentik
              url: https://auth.${domain}
              key: CHANGE_ME_HOMEPAGE_AUTHENTIK_API_KEY

    - Media:
        - Jellyfin:
            href: https://media.${domain}
            description: Media server
            icon: jellyfin
            widget:
              type: jellyfin
              url: https://media.${domain}
              key: CHANGE_ME_JELLYFIN_API_KEY
        - Immich:
            href: https://photos.${domain}
            description: Photo library
            icon: immich
            widget:
              type: immich
              url: https://photos.${domain}
              key: CHANGE_ME_IMMICH_API_KEY

    - Files & Sync:
        - Nextcloud:
            href: https://cloud.${domain}
            description: File sync & collaboration
            icon: nextcloud
            widget:
              type: nextcloud
              url: https://cloud.${domain}
              username: admin
              password: CHANGE_ME_NEXTCLOUD_ADMIN_PASS
        - Syncthing:
            href: https://sync.${domain}
            description: Continuous file sync
            icon: syncthing

    - Downloads:
        - qBittorrent:
            href: https://torrent.${domain}
            description: Torrent client
            icon: qbittorrent
        - Bitmagnet:
            href: https://bitmagnet.${domain}
            description: DHT crawler & search (on-demand)
            icon: bitmagnet

    - Automation:
        - Home Assistant:
            href: https://ha.${domain}
            description: Home automation
            icon: home-assistant
            widget:
              type: homeassistant
              url: https://ha.${domain}
              key: CHANGE_ME_HA_LONG_LIVED_TOKEN
        - Zigbee2MQTT:
            href: https://zigbee.${domain}
            description: Zigbee bridge
            icon: zigbee2mqtt

    - Surveillance:
        - Frigate:
            href: https://nvr.${domain}
            description: NVR & object detection
            icon: frigate

    - Monitoring:
        - Grafana:
            href: https://grafana.${domain}
            description: Metrics dashboards
            icon: grafana
            widget:
              type: grafana
              url: https://grafana.${domain}
              username: admin
              password: CHANGE_ME_GRAFANA_ADMIN_PASS

    - Utilities:
        - Vaultwarden:
            href: https://vault.${domain}
            description: Password manager
            icon: vaultwarden
        - SearXNG:
            href: https://search.${domain}
            description: Metasearch engine
            icon: searxng
        - Snapcast:
            href: https://audio.${domain}
            description: Multi-room audio
            icon: snapcast
  '';

  settingsYaml = pkgs.writeText "homepage-settings.yaml" ''
    title: Homelab
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Identity & Auth:
        icon: mdi-shield-account
      Media:
        icon: mdi-television-play
      Files & Sync:
        icon: mdi-folder-sync
      Downloads:
        icon: mdi-download
      Automation:
        icon: mdi-home-automation
      Surveillance:
        icon: mdi-cctv
      Monitoring:
        icon: mdi-chart-line
      Utilities:
        icon: mdi-tools
  '';

  widgetsYaml = pkgs.writeText "homepage-widgets.yaml" ''
    - resources:
        cpu: true
        memory: true
        disk: /
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
  '';

in
{
  virtualisation.oci-containers.containers."homepage" = {
    image = "ghcr.io/gethomepage/homepage:latest";

    volumes = [
      "${servicesYaml}:/app/config/services.yaml:ro"
      "${settingsYaml}:/app/config/settings.yaml:ro"
      "${widgetsYaml}:/app/config/widgets.yaml:ro"
      # Caddy's internal CA root cert — required for widget TLS verification.
      # Generated by Caddy on first TLS request; widgets error until it exists.
      # The ExecStartPre below makes root.crt world-readable so the rootless
      # homepage user can bind-mount it.
      "/var/lib/caddy/.local/share/caddy/pki/authorities/local:/caddy-ca:ro"
    ];

    extraOptions = [ "--network=host" ];

    environment = {
      HOMEPAGE_ALLOWED_HOSTS = "home.${domain},localhost";
      # Trust Caddy's internal CA for all outbound HTTPS widget requests.
      NODE_EXTRA_CA_CERTS = "/caddy-ca/root.crt";
    };

    podman.user = "homepage";
    user = "0";
    autoStart = true;
  };

  # Start Homepage after Caddy so the CA cert is more likely to exist.
  # The ExecStartPre (root) makes the CA cert world-readable so the rootless
  # homepage user can pass it through as a bind-mount volume.
  systemd.services."podman-homepage" = {
    after  = [ "caddy.service" ];
    wants  = [ "caddy.service" ];
    serviceConfig.ExecStartPre = [
      "+${pkgs.writeShellScript "homepage-fix-ca-perms" ''
        set -euo pipefail
        # Rootless Podman (running as 'homepage' UID) must be able to statfs every
        # parent directory of the bind-mount source.  Caddy's state dir is 0700, so
        # we grant o+x all the way down.  We do this unconditionally whenever Caddy
        # has created the PKI structure — the cert file itself may not exist yet on
        # first boot (Caddy generates it lazily on the first TLS request).
        CERT_DIR=/var/lib/caddy/.local/share/caddy/pki/authorities/local
        if [ -d "$CERT_DIR" ]; then
          chmod o+x /var/lib/caddy
          chmod o+x /var/lib/caddy/.local
          chmod o+x /var/lib/caddy/.local/share
          chmod o+x /var/lib/caddy/.local/share/caddy
          chmod o+x /var/lib/caddy/.local/share/caddy/pki
          chmod o+x /var/lib/caddy/.local/share/caddy/pki/authorities
          chmod o+x "$CERT_DIR"
          [ -f "$CERT_DIR/root.crt" ] && chmod o+r "$CERT_DIR/root.crt"
        fi
      ''}"
    ];
  };
}
