# hosts/server/services/tang.nix
#
# Tang key server — the trust anchor for Raspberry Pi Clevis LUKS unlock.
#
# ─────────────────────────────────────────────────────────────────────────────
# HOW IT WORKS
# ─────────────────────────────────────────────────────────────────────────────
#
#  Tang holds an asymmetric key pair used as an unlock factor by Clevis on the
#  Raspberry Pi. At unlock time, the Pi sends a key-derivation request to Tang;
#  Tang responds; Clevis combines the response with the LUKS key material to
#  open the NVMe volumes. No raw key material leaves either side.
#
# ─────────────────────────────────────────────────────────────────────────────
# SECURITY GATING
# ─────────────────────────────────────────────────────────────────────────────
#
#  Tang MUST NOT serve keys until the control LUKS layer is manually unlocked.
#  This is enforced by modules/server/secure-layers.nix:
#
#    1. Tang keys live in /mnt/control/tang/ on the control LUKS partition.
#    2. /var/lib/tang is a bind mount from /mnt/control/tang (noauto).
#    3. tangd.socket has WantedBy=control-online.target (not sockets.target).
#    4. ConditionPathIsMountPoint=/var/lib/tang prevents Tang from activating
#       if the bind mount is not in place (defence in depth).
#
#  Result: if someone reboots the server and does not enter the control
#  passphrase, Tang remains unreachable and the Pi's NVMe volumes stay locked.
#
# ─────────────────────────────────────────────────────────────────────────────
# KEY MANAGEMENT
# ─────────────────────────────────────────────────────────────────────────────
#
#  Keys are auto-generated by Tang on first start if /var/lib/tang is empty.
#  IMPORTANT: this means the very first unlock-control initialises a fresh Tang
#  identity. Back up /var/lib/tang (= /mnt/control/tang) IMMEDIATELY after
#  the first start. See docs/runbook.md § "Backing up Tang keys".
#
#  Key rotation:
#    tangd-keygen /var/lib/tang    # generate a new key pair
#    # Keep the old key for a transition window (Pi re-bind takes time).
#    # After re-binding all Pi volumes: remove the old key files.
#
#  After rotation, re-bind each Pi NVMe volume:
#    clevis luks regen -d /dev/disk/by-id/<drive> -s <slot>
#
#  Tang identity is preserved across reboot/restore as long as /mnt/control/tang
#  contains the same key files. See docs/runbook.md § "Restore order".
#
#  The system NEVER silently generates a fresh Tang identity during a normal
#  reboot — keys are regenerated only if /var/lib/tang is empty, which only
#  happens if the control backup was lost or the control LUKS was re-formatted.
#
{ ... }:

{
  services.tang = {
    enable = true;
    # Port 7500 is the default in the NixOS Tang module.
    # The server firewall allows this port (see hosts/server/default.nix).
    # The socket is gated on control-online.target by secure-layers.nix —
    # do not add socket overrides here to avoid attribute conflicts.
    listenStream = [ "0.0.0.0:7500" "[::]:7500" ];
    # Firewall already restricts port 7500 to the LAN; allow all at socket level.
    ipAddressAllow = [ "any" ];
  };

  # KEY BACKUP REMINDER: /mnt/control/tang must be backed up.
  # See modules/server/backups.nix for the control backup timer.
}
